services:
  portfolio:
    build: .
    ports:
      - "5000:80"
    container_name: portfolio-website
    volumes:
      - .:/usr/src/app
    networks:
      - mynet

  

networks:
  mynet:
    driver: bridge
